### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by ChaseTaylor939** [combio-dku/HiCAT#1]
Quick question on the cell_markers_rndsystems.tsv file concerning abbreviations.  What does exp stand for?  Also, what does sec stand for?
Thank you,
Chase

**Comment by combio-dku** [comment]
Hi, Chase
'exp' field indicates the type of expressed markers, which can be one of 'pos', 'neg' or 'sec', where 'sec' means secretory factor, such as cytokines (ILxx) or chemokines (CXCLxx). The detailed description on the marker can be found in the supplementary file 1 of the HiCAT paper, https://doi.org/10.1093/bib/bbad006. (page 4. Construction of marker database)

You can select their inclusion by setting the 'mkr_selector' parameter. 
It is a string of length 6, consisting of 0 or 1, e.g., '100000'.  Each binanry number corresponds to the inclusion of 'pos', 'neg', 'sec', 'mhc', 'mhc-1', 'mhc-2', respectively, in that order. The default value is '100000', i.e., HiCAT use only positive markers. As shown in the supplemental file 1, Fig 5~7, secretory factor does not well represent the cell states. So, I recommend to use only positive markers (for now).

Seokhyun
