### ISSUE TITLE
Could you please give more datasets? thanks.

### ISSUE THREAD

**Issue by xuewenm** [combio-dku/HiCAT#4]
Hello, I'm an undergraduate student and I'm very interested in your work. However, it seems quite difficult to find hierarchical datasets related to single-cell. Could you please provide more information about the datasets used in your paper to help me further my experiments in this field?

**Comment by combio-dku** [comment]
Hi Xuewen
Sorry for very late reply.
I guess you are looking for single-cell datasets that provide celltype annotation in hierarchical manner.
As I know two datasets provide celltype annotation in hierarchical manner (GSE176078 and SCP259)
They were used in my HiCAT paper. However, as noted, it's quite difficult to use their subset annotation results for performance evaluation. 
If you didn't mean it, please let me know.
