### ISSUE TITLE
mkrcnt$HiCAT py_call_impl ERROR

### ISSUE THREAD

**Issue by gianfilippo** [combio-dku/HiCAT#5]
Hi,
I am getting the following error on one of my 12 samples. The other 11 samples are ok
I run it as follow
lst_res <- mkrcnt$HiCAT(X_test, marker_file=mkr_file, log_transformed=F)

dim(X_test)
[1]  3773 27554

HiCAT running ...P3.C1...M10...M22..Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: Expected n_samples >= n_components but got n_components = 25, n_samples = 23
Run `reticulate::py_last_error()` for details.

What do you think ?
Thanks

**Comment by combio-dku** [comment]
Hi 
It seems to be a bug.
I'll try to fix it asap.
Can you send me the data you got error?
With the data, I can make sure the correction is complete.
If you don't want to post its link here, you can send me an email to syoon@dku.edu

**Comment by gianfilippo** [comment]
Hi,

thanks. I just sent you the input matrix on your email

Best

**Comment by combio-dku** [comment]
Hi, Gianfilippo
I have just fixed HiCAT code.
Just reinstall MarkerCount package (pip install MarkerCount --upgrade)
and try to rerun with your data.
Please let me know if you still get error.

**Comment by gianfilippo** [comment]
Thanks!

I will let you know when I test it

Best

**Comment by gianfilippo** [comment]
Hi,

I am now getting an error (see below) on a different sample. What do you
think ?
Best

HiCAT running ...P3.C0...M7...M22..Error in py_call_impl(callable,
call_args$unnamed, call_args$named) :

  UnboundLocalError: local variable 'm1' referenced before assignment

Run `reticulate::py_last_error()` for details.

In addition: Warning messages:

1: In asMethod(object) :

  sparse->dense coercion: allocating vector of size 1.5 GiB

2: In asMethod(object) :

  sparse->dense coercion: allocating vector of size 1.0 GiB

**Comment by combio-dku** [comment]
I just updated the code.
I'm not sure I corrected right places.
Just reinstall MarkerCount package and try to rerun with your data. (It is now v0.7.1.)
Please let me know if you still get error.

**Comment by gianfilippo** [comment]
it looks like it is working now.
Thanks for your help!
Best
